doc-warnings: true
test-warnings: false
strictness: medium
max-line-length: 80
autodetect: true
ignore-paths:
  - data
  - docs
  - figures
  - logs
  - models
  - notebooks
  - references
python-targets:
  - 3