# Disable sudo to speed up the build
sudo: false

language: python
  
env: 
   global:
      - OFFICIAL_REPO="{{ cookiecutter.author_name }}/{{ cookiecutter.repo_name }}"
      - BUILD_DOCS=1
      - secure: ""

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"    
  
install:
  # Download Conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Grab all dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip wheel pytest
  # Launch Conda environment
  - source activate test-environment
  # Install the requirements
  - pip install -r requirements.txt -r dev-requirements.txt

script:
  - python run_tests.py
  - flake8 {{ cookiecutter.repo_name }}
  - set -e  
  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY_{{ cookiecutter.author_name.upper() }}_{{ cookiecutter.repo_name.upper() }}" && $BUILD_DOCS ]]; then
    # Install the requirements to build the documentation
    conda install --file docs-requirements.txt -c anaconda -c conda-forge
    # Create HTML documentation  
    pushd docs
    make html
    popd
    # Publish docs.
    doctr deploy . --built-docs docs/_build/html --deploy-branch-name gh-pages
    fi

after_success:
  - codecov
